server {
    listen 80;
    server_name go2rtc.geek;

    resolver 127.0.0.11 valid=30s;

    location / {
        set $upstream http://geek-go2rtc:1984;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
