services:
  magicmirror:
    image: karsten13/magicmirror:latest
    container_name: geek-magicmirror
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /srv/homelab/magicmirror/config:/opt/magic_mirror/config
      - /srv/homelab/magicmirror/modules/MMM-Jast:/opt/magic_mirror/modules/MMM-Jast
      - /srv/homelab/magicmirror/modules/MMM-Wallpaper:/opt/magic_mirror/modules/MMM-Wallpaper
      - /srv/homelab/magicmirror/css/custom.css:/opt/magic_mirror/css/custom.css
    networks:
      - geek-infra

networks:
  geek-infra:
    external: true
