---
- name: Restart MagicMirror
  community.docker.docker_compose_v2:
    project_src: /home/johnb/homelab-admin/platform/magicmirror
    state: present
    recreate: always
  become: yes

- name: Restart GDM
  systemd:
    name: gdm
    state: restarted
  become: yes

- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes
