---
- name: Restart MagicMirror
  community.docker.docker_compose_v2:
    project_src: /home/johnb/homelab-admin/platform/magicmirror
    state: present
    recreate: always
  become: yes

- name: Restart GDM
  systemd:
    name: gdm
    state: restarted
  become: yes

- name: Reload user systemd
  shell: |
    uid=$(id -u johnb)
    sudo -u johnb \
      XDG_RUNTIME_DIR=/run/user/$uid \
      DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$uid/bus \
      systemctl --user daemon-reload
  become: yes
